CC=g++
CFLAGS=-o -Wall
# BINS=a
# all: $(BINS)

# %: %.cpp
# 	$(CC) $(CFLAGS) $^ -o $@

clean:
	$(RM) -r a b c d *.dSYM

d: d.cpp
	$(CC) $(CFLAGS) d.cpp -o d

b: b.cpp
	$(CC) $(CFLAGS) b.cpp -o b

c: c.cpp
	$(CC) $(CFLAGS) c.cpp -o c

e: e.cpp
	$(CC) $(CFLAGS) e.cpp -o e

